function y_item_detail_modalUI(){
	return '<div class="mfp-wrap white-popup" id="y_item_detailUI">'
	+'	<div class="mfp-container detail-main text-center">    ' //
	+'	   	<div class="col-sm-8 mfp-content" >'//class="mfp-content"
	+'	      	<div class="col-sm-8 text-left"> '
	+'	         	<div class="container">'
	+'		            <br/><br/><br/><br/>     '
	+'		            <img src="/web/resources/img/yoonho/maehwa_chicken.jpg" height="800" width="800" class="img-rounded text-center"> '
	+'					<br/> '
	+'					<hr>'
	+'					<br/><br/><br/>'
	+''
	+'					<!-- Comment Area Start -->'
	+'					<div class="comment_area section_padding_50 clearfix">'
	+'		                <h4 class="mb-30">2개의 댓글이 작성되었습니다.</h4><br/><br/><br/>'

	+'		                <ol>'
	+''
	+'							<!-- Single Comment Area -->'
	+'		                	<li class="single_comment_area">'
	+'			                    <div class="comment-wrapper d-flex">'
				                    	+''
	+'			                    	<!-- Comment Meta -->'
	+'			                    	<div class="comment-author">'
	+'			                        	<img src="/web/resources/img/yoonho/img_avatar1.png" height="40" width="40" class="img-circle">'
	+'			                    	</div>'
				                    	+''
	+'			                    	<!-- Comment Content -->'
	+'			                    	<div class="comment-content">'
	+'				                        <br/>'
	+'				                        <span class="comment-date text-muted">27 Aug 2018</span>'
	+'				                        <h5>맛짱</h5>'
	+'				                        <div>'

	+'	<!-- rating star -->'
	+'	<span class="star-input">'
	+'		<span class="input">'
	+'			<input type="radio" name="star-input" id="p1" value="1"><label for="p1">1</label>'
	+'			<input type="radio" name="star-input" id="p2" value="2"><label for="p2">2</label>'
	+'			<input type="radio" name="star-input" id="p3" value="3"><label for="p3">3</label>'
	+'			<input type="radio" name="star-input" id="p4" value="4"><label for="p4">4</label>'
	+'			<input type="radio" name="star-input" id="p5" value="5"><label for="p5">5</label>'
	+'			<input type="radio" name="star-input" id="p6" value="6"><label for="p6">6</label>'
	+'			<input type="radio" name="star-input" id="p7" value="7"><label for="p7">7</label>'
	+'			<input type="radio" name="star-input" id="p8" value="8"><label for="p8">8</label>'
	+'			<input type="radio" name="star-input" id="p9" value="9"><label for="p9">9</label>'
	+'			<input type="radio" name="star-input" id="p10" value="10"><label for="p10">10</label>'
	+'		</span>'
	+'		<output for="star-input"><b>0</b>점</output>'
	+'	</span>'
	
	+'				                        </div>'
	+'				                        <p>매화도시락 너무 비싸요 음식점에서 사먹는가격보다 비쌈..</p>'
	+'				                        <span class="glyphicon glyphicon-thumbs-up"></span>'
	+'				                        <a href="#" class="btn btn-warning" role="button">수정<a/>'
	+'			                    	</div>'
	+''
	+'			                    </div>'
	+'		                	</li>'
	+'		           			<hr>'
	+''
	+'		           			<!-- Single Comment Area 2 -->'
	+'		                 	<li class="single_comment_area">'
	+'		                    	<div class="comment-wrapper d-flex">'
	+''
	+'			                      	<!-- Comment Meta -->'
	+'			                      	<div class="comment-author">'
	+'		                        		<img src="/web/resources/img/yoonho/img_avatar3.png" height="40" width="40" class="img-circle">'
	+'		                      		</div>'
	+''
	+'				                    <!-- Comment Content -->'
	+'				                    <div class="comment-content">'
	+'				                        <br/>'
	+'				                        <span class="comment-date text-muted">27 Aug 2018</span>'
	+'				                        <h5>바빠바빠너무바빠</h5>'
	+'				                        <div>'

	+'	<!-- rating star -->'
	+'	<span class="star-input">'
	+'		<span class="input">'
	+'			<input type="radio" name="star-input" id="p1" value="1"><label for="p1">1</label>'
	+'			<input type="radio" name="star-input" id="p2" value="2"><label for="p2">2</label>'
	+'			<input type="radio" name="star-input" id="p3" value="3"><label for="p3">3</label>'
	+'			<input type="radio" name="star-input" id="p4" value="4"><label for="p4">4</label>'
	+'			<input type="radio" name="star-input" id="p5" value="5"><label for="p5">5</label>'
	+'			<input type="radio" name="star-input" id="p6" value="6"><label for="p6">6</label>'
	+'			<input type="radio" name="star-input" id="p7" value="7"><label for="p7">7</label>'
	+'			<input type="radio" name="star-input" id="p8" value="8"><label for="p8">8</label>'
	+'			<input type="radio" name="star-input" id="p9" value="9"><label for="p9">9</label>'
	+'			<input type="radio" name="star-input" id="p10" value="10"><label for="p10">10</label>'
	+'		</span>'
	+'		<output for="star-input"><b>0</b>점</output>'
	+'	</span>'
	
	+'		                        		</div>'
	+'			                        	<p>바쁜 저녁 마라톤회의때 먹었는데 든든합니다. 강추!!</p>'
	+'			                          	<span class="glyphicon glyphicon-thumbs-up"></span>'
	+'			                        	<a href="#" class="btn btn-warning" role="button">신고<a/>'
	+'		                      		</div>'
	+''
	+'		                    	</div>'
	+'		                  	</li>'
	+''
	+'	                	</ol>'
	+'	              	</div>'
	+''
		            +''
	+'	              	<!-- Leave A Comment -->'
	+'	              	<div class="leave-comment-area section_padding_50 clearfix">'
	+'		                <div class="comment-form">'
	+'		                  	<h4 class="mb-30">Comment</h4>'
			            +''
	+'		                  	<!-- Comment Form -->'
	+'		                  	<form action="#" method="post">'
	+'		                    	<div class="form-group">'
	+'		                      		<textarea class="form-control" name="message" id="message" cols="30" rows="10" placeholder="댓글을 입력하세요"></textarea>'
	+'		                    	</div>'
	+'		                    	<button type="submit" class="btn btn-warning">Post Comment</button>'
	+'		                  	</form>'
	+''
	+'		                </div>'
	+'	              	</div>'
	+''
	+'				</div>'
	+'			</div>'
	+'		</div>'
	+'	</div>'
	+''
	+'	<!-- detail right mfp-navi -->'
	+'	<div class="col-sm-5 detail-right mfp-navi">'//detail-right
	+'<!-- item fixed navi UI -->'
	+'<div class="container-fluid">'
	+'    <div class="row">'
	+'		<div class="col-lg-12" style="background-color:#f1f1f1;"><!-- border:1px solid #444444;-->'
	+'			<h1 class="text-center">매화 (치킨, 연어구이)</h1>'
	+'			<p class="text-center">사각 도시락</p>'


	+'	<!-- rating star -->'
	+'	<span class="star-input">'
	+'		<span class="input">'
	+'			<input type="radio" name="star-input" id="p1" value="1"><label for="p1">1</label>'
	+'			<input type="radio" name="star-input" id="p2" value="2"><label for="p2">2</label>'
	+'			<input type="radio" name="star-input" id="p3" value="3"><label for="p3">3</label>'
	+'			<input type="radio" name="star-input" id="p4" value="4"><label for="p4">4</label>'
	+'			<input type="radio" name="star-input" id="p5" value="5"><label for="p5">5</label>'
	+'			<input type="radio" name="star-input" id="p6" value="6"><label for="p6">6</label>'
	+'			<input type="radio" name="star-input" id="p7" value="7"><label for="p7">7</label>'
	+'			<input type="radio" name="star-input" id="p8" value="8"><label for="p8">8</label>'
	+'			<input type="radio" name="star-input" id="p9" value="9"><label for="p9">9</label>'
	+'			<input type="radio" name="star-input" id="p10" value="10"><label for="p10">10</label>'
	+'		</span>'
	+'		<output for="star-input"><b>0</b>점</output>'
	+'	</span>'
	 
	
	+'			<p class="text-left">1520명이 평가했어요</p>'
	+'			<p role="button" class="glyphicon glyphicon-thumbs-up" >(743명)</p>'
	+'		</div>'
	+'	</div>'
	+'	<div class="row">'
	+''
	+'		<div class="col-lg-8" style="background-color:beige;"><!-- border:1px solid #444444;-->'
	+'			<table>'
	+'				<tr>'
	+'					<td class="text-left">'
	+'						업  체'
	+'					</td>'
	+'					<td class="text-right">'
	+'						오봉도시락'
	+'					</td>'
	+'				</tr>'
	+'				<tr>'
	+'					<td class="text-left">'
	+'						칼로리'
	+'					</td>'
	+'					<td class="text-right">'
	+'						405.5Kcal'
	+'					</td>'
	+'				</tr>'
	+'				<tr>'
	+'					<td class="text-left">'
	+'						가  격'
	+'					</td>'
	+'					<td class="text-right">'
	+'						10,000 원'
	+'					</td>'
	+'				</tr>'
	+'			</table>'
	+'			<hr/>'
	+'			<p class="text-left">'
				    +'[베스트 & 스테디셀러 SINCE 2007] 12가지 다양한 반찬으로 구성된 프리미엄 도시락입니다. 푸짐한 반찬과 함께 촉촉하고 부드러운 연어구이와 치킨이 구성되어 있어 부족하지 않고 든든하게 드실 수 있는 도시락 입니다. 생수와 조미 김이 함께 제공 됩니다.'
	+'			</p>'
	+'			<p role="button" class="text-right">#고소</p>'
	+'			<p role="button" class="text-right">#달콤</p>'
	+'		</div>'
	+'		<div class="col-lg-4" style="background-color:beige;"><!-- border:1px solid #444444;-->'
	+'			<br/>'
	+'			<br/>'
	+'			알러지 정보'
	+'			<br/>'
	+'			<hr/>'
	+'			그림들'
	+'			<br/>'
	+'			<br/>'
	+'			<br/>'
	        +''
	+'      	</div>'
	+'    </div>'
	+'    <div class="row">'
	+'		<div class="col-lg-12" style="background-color:#f1f1f1; "><!-- border:1px solid #444444;-->'
	+''
	+'			<h2>Clickable Dropdown</h2>'
	+'			<p>Click on the button to open the dropdown menu.</p>'
	+''
	+'			<div class="dropdown">'
	+'				<button onclick="myFunction()" class="dropbtn">Dropdown</button>'
	+'				<div id="myDropdown" class="dropdown-content">'
	+'					<a href="#home">같은 종류의 도시락</a>'
	+'					<a href="#about">About</a>'
	+'					<a href="#contact">Contact</a>'
	+'				</div>'
	+'			</div>'
	+''
	+''
	+'		</div>'
	+'    </div>'
	+'</div>'
	+'	</div>'
	+''
	+'</div>'
	
	
	
	
	
	
	
	
	
	
	
	
	
	+'<!-- JS script yoonho.js에 추가하고 script 지울것 -->'
	+'<script>'
	+'/* When the user clicks on the button, toggle between hiding and showing the dropdown content */'
	+'function myFunction() {'
	+'    document.getElementById("myDropdown").classList.toggle("show");'
	+'}'
	+''
	+'// Close the dropdown if the user clicks outside of it'
	+'window.onclick = function(event) {'
	+'	if (!event.target.matches(".dropbtn")) {'
	+''
	+'		var dropdowns = document.getElementsByClassName("dropdown-content");'
	+'		var i;'
	+'		for (i = 0; i < dropdowns.length; i++) {'
	+'			var openDropdown = dropdowns[i];'
	+'			if (openDropdown.classList.contains("show")) {'
	+'				openDropdown.classList.remove("show");'
	+'			}'
	+'		}'
	+'	}	'
	+'}'
	
	+'/* When the user clicks on the button, Star is rated*/'
	+'	var starRating = function(){'
	+'		var $star = $(".star-input"),'
	+'			$result = $star.find("output>b");'
	+'		$(document)'
	+'		.on("focusin", ".star-input>.input", function(){'
	+'			$(this).addClass("focus");'
	+'		})'
	+'		.on("focusout", ".star-input>.input", function(){'
	+'			var $this = $(this);'
	+'			setTimeout(function(){'
	+'				if($this.find(":focus").length === 0){'
	+'					$this.removeClass("focus");'
	+'				}'
	+'			}, 100);'
	+'		})'
	+'		.on("change", ".star-input :radio", function(){'
	+'			$result.text($(this).next().text());'
	+'		})'
	+'		.on("mouseover", ".star-input label", function(){'
	+'			$result.text($(this).text());'
	+'		})'
	+'		.on("mouseleave", ".star-input>.input", function(){'
	+'			var $checked = $star.find(":checked");'
	+'			if($checked.length === 0){'
	+'				$result.text("0");'
	+'			} else {'
	+'				$result.text($checked.next().text());'
	+'			}'
	+'		});'
	+'	};'
	+'	starRating();'

	
	+'</script>'
;


}